# .goreleaser.yml
# Visit https://goreleaser.com/customization/ for more options

# The name of your project.
# Defaults to the repository name.
project_name: fetch-go

# before hooks are commands that are executed before the build
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy

# Build configuration
builds:
  - # The main Go file to build.
    # Defaults to the main.go file in the root of the repository.
    main: main.go

    # The binary name.
    # Defaults to the project name.
    binary: fetch-go

    # GOOS and GOARCH to build for.
    # Defaults to the current system's GOOS and GOARCH.
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

    # Environment variables to use during the build.
    env:
      - CGO_ENABLED=0

# Archive configuration
archives:
  - # The format of the archive.
    # Can be 'tar.gz', 'zip', or 'binary'.
    # 'binary' is only valid when there is only one build.
    # Defaults to 'tar.gz'.
    format: tar.gz

    # The name template for the archive.
    # Defaults to '{{.ProjectName}}_{{.Version}}_{{.Os}}_{{.Arch}}'.
    name_template: "{{.ProjectName}}_{{.Version}}_{{.Os}}-{{.Arch}}"

    # Files to include in the archive.
    files:
      - LICENSE
      - README.md

# Checksum configuration
checksum:
  # The name of the checksum file.
  # Defaults to '{{.ProjectName}}_{{.Version}}_checksums.txt'.
  name_template: '{{.ProjectName}}_{{.Version}}_checksums.txt'

# Snapshot configuration
snapshot:
  # The name of the snapshot.
  # Defaults to 'SNAPSHOT-{{.ShortCommit}}'.
  name_template: "{{.Version}}-dev-{{.ShortCommit}}"

# Changelog configuration
changelog:
  # Sorts the changelog by 'asc' or 'desc'.
  # Defaults to 'asc'.
  sort: asc
  # Filters the changelog.
  filters:
    # Excludes commit messages that match the given regex.
    exclude:
      - '^docs:'
      - '^test:'
